#pragma once

const int SCREEN_WIDTH = 1920;
const int SCREEN_HEIGHT = 1080;

const int ENGINE_POLLING_RATE = 90; // POLLS PER SECOND
const int VIEW_POLLING_RATE = 120; // SCREEN REFRESH RATE
const int VIEW_INPUT_POLLING_RATE = 120; // INPUT POLLING RATE