#pragma once

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define ENGINE_POLLING_RATE 60 // POLLS PER SECOND
#define VIEW_POLLING_RATE 244 // SCREEN REFRESH RATE
#define VIEW_INPUT_POLLING_RATE 24