#pragma once

const int SCREEN_WIDTH = 1280;
const int SCREEN_HEIGHT = 720;

const int ENGINE_POLLING_RATE = 60; // POLLS PER SECOND
const int VIEW_POLLING_RATE = 244; // SCREEN REFRESH RATE
const int VIEW_INPUT_POLLING_RATE = 243; // INPUT POLLING RATE